### ISSUE TITLE
@GtkSourceMap not defined

### ISSUE THREAD

**Issue by lucianolorenti** [jonathanBieler/GtkIDE.jl#6]
I'm having an issue with the GtkSourceMap. I'm using Linux Mint 17.3. 

`ERROR: LoadError: LoadError: UndefVarError: @GtkSourceMap not defined`

I'm evading it removing every mention of GtkSourceMap: 
In the datatype of the   sourcemap  member of the Editor type  and in:

> ```
>     if GtkSourceWidget.SOURCE_MAP #old linux libraries don't have GtkSourceMap
> -       sourcemap = @GtkSourceMap()
> +       sourcemap=nothing
>         t = new(ntbook.handle,sourcemap)
>     else
> -       t = new(ntbook.handle)
> +       t = new(ntbook.handle,nothing)
>     end
> ```

I'm not sure how is the correct way to solve it.

**Comment by jonathanBieler** [comment]
This should fix it:

https://github.com/jonathanBieler/GtkIDE.jl/commit/9287541b6c7e83791d2afe39719fe33cb3100fe3

**Comment by lucianolorenti** [comment]
I think is still missing the initialization of the sourcemap field  in the constructor. Otherwise it gives me an undefined reference in the line 81 of  GtkIDE.jl.

**Comment by jonathanBieler** [comment]
Right, I removed the check in GtkIDE.jl and fused it with the constructor.
